trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# - script: |
#     python -m pytest tests
#   displayName: 'Run tests'

# # Assuming your build process creates an artifact in a folder named 'build_output'
# - script: |
#     # Your build command here, for example:
#     python setup.py build
#   displayName: 'Build Project'

# Publish the artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build_output'  # The folder path of the artifact to publish
    ArtifactName: 'myArtifact'  # Name of the artifact
    publishLocation: 'Container'